# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site 
baseurl: 

# Title of the Site
title: Lightcaster Studios
# Description of the Site
description: Website for Lightcaster Studios projects
# URL of Image of the Site
site-image: /WhatATheme/assets/images/Banner_Plain.jpg
# Keywords of the Site
site-keywords:
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  lightcaster-studios
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Lightcaster Studios
# URL for the Image of the Author
author-image: 
# 60 Words About the Author
author-about: Lightcaster Studios is an upcoming indie game studio.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/lightcaster-studios

# toc
# _config.yml
toc:
  min_level: 1
  max_level: 3
  ordered_list: true
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-toc

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

livereload: true

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
